-- 名称与条件来自游戏的 Steam 成就本地化资源。
return {
    {id="ACHIEVEMENT_001", name="天下无双的剑豪", description="解锁所有成就", english_name="Peerless", hidden=false, english_description="Unlock all achievements.", group=4},
    {id="ACHIEVEMENT_002", name="鬼武者对决", description="击退佐佐木岩流", english_name="Onimusha Showdown", hidden=true, english_description="Drive off Sasaki Ganryu.", group=4},
    {id="ACHIEVEMENT_003", name="老吃家", description="击败大唾拉", english_name="Get Stuffed", hidden=true, english_description="Defeat Daidara.", group=4},
    {id="ACHIEVEMENT_004", name="扭曲的如愿以偿", description="击败罗掌愿", english_name="Twisted Fates", hidden=true, english_description="Defeat Rasho-gan.", group=4},
    {id="ACHIEVEMENT_005", name="小心暴风", description="击败畏风", english_name="Howling Wind", hidden=true, english_description="Defeat Ifuu.", group=4},
    {id="ACHIEVEMENT_006", name="道狂的心头好", description="击败大鵺", english_name="Dokyo's Fixation", hidden=true, english_description="Defeat the Greater Nue.", group=4},
    {id="ACHIEVEMENT_007", name="屹立而逝的弁庆", description="击败弁庆", english_name="Benkei: Out, but Not Down", hidden=true, english_description="Defeat Benkei.", group=4},
    {id="ACHIEVEMENT_008", name="电光石火", description="击败抚雷", english_name="Crashing Lightning", hidden=true, english_description="Defeat Burai.", group=4},
    {id="ACHIEVEMENT_009", name="完全觉醒", description="击败酒吞童子", english_name="Wide Awake", hidden=true, english_description="Defeat Shuten Doji.", group=4},
    {id="ACHIEVEMENT_010", name="迅雷风烈", description="击败畏风与抚雷", english_name="The Perfect Storm", hidden=true, english_description="Defeat Ifuu and Burai.", group=4},
    {id="ACHIEVEMENT_011", name="因果的尽头", description="在岚山击败佐佐木岩流", english_name="We Done Here?", hidden=true, english_description="Defeat Sasaki Ganryu at Arashiyama.", group=4},
    {id="ACHIEVEMENT_012", name="癫狂至极", description="击败道狂", english_name="End This Madness", hidden=true, english_description="Defeat Dokyo.", group=4},
    {id="ACHIEVEMENT_013", name="谋略", description="在莲台野击败弁庆", english_name="Baited by Benkei", hidden=true, english_description="Defeat Benkei at Rendaino.", group=4},
    {id="ACHIEVEMENT_014", name="真心感谢", description="击败源义经", english_name="Truly, Thank You", hidden=true, english_description="Defeat Minamoto no Yoshitsune.", group=4},
    {id="ACHIEVEMENT_015", name="京都奇谭", description="第一次完成京都奇谭", english_name="Mystery Solved", hidden=false, english_description="Complete your first Mystery of Kyoto.", group=2},
    {id="ACHIEVEMENT_016", name="扣人心弦的故事", description="完成所有京都奇谭", english_name="Demystified", hidden=false, english_description="Complete all Mysteries of Kyoto.", group=2},
    {id="ACHIEVEMENT_017", name="唯一的指望", description="第一次完成一树之荫", english_name="Life-Saver", hidden=false, english_description="Complete your first Chance Encounter.", group=2},
    {id="ACHIEVEMENT_018", name="麻烦事我包了", description="完成所有一树之荫", english_name="No Job Too Small", hidden=false, english_description="Complete all Chance Encounters.", group=2},
    {id="ACHIEVEMENT_019", name="算你狠", description="击败清水寺的百秽", english_name="Serves You Right", hidden=false, english_description="Defeat the Byakue at Kiyomizu-dera Temple.", group=2},
    {id="ACHIEVEMENT_020", name="救助居民", description="救下30名遭幻魔袭击的居民", english_name="Citizen Savior", hidden=false, english_description="Rescue 30 townspeople from marauding Genma.", group=2},
    {id="ACHIEVEMENT_021", name="善有善报", description="救下遭幻魔袭击的商人", english_name="Selfish Selflessness", hidden=false, english_description="Rescue a merchant that's being attacked by Genma.", group=2},
    {id="ACHIEVEMENT_022", name="救救小狗", description="第一次救助狛犬", english_name="No Dog Left Behind", hidden=false, english_description="Rescue your first Lion Dog.", group=2},
    {id="ACHIEVEMENT_023", name="关爱狗狗", description="救助所有狛犬", english_name="For the Love of Dog", hidden=false, english_description="Rescue all the Lion Dogs.", group=2},
    {id="ACHIEVEMENT_024", name="幻魔专家", description="集齐所有幻魔杂记", english_name="Genma-ologist", hidden=false, english_description="Collect all the Genma notes.", group=2},
    {id="ACHIEVEMENT_025", name="真正的鬼武者", description="在“鬼杀”难度下通关游戏", english_name="True Onimusha", hidden=true, english_description="Complete the game on difficulty level \"Carnage\".", group=4},
    {id="ACHIEVEMENT_026", name="强敌再袭", description="在“再战强敌”中击败1名敌人", english_name="Second Helping", hidden=true, english_description="Beat an opponent in a Boss Rematch.", group=4},
    {id="ACHIEVEMENT_027", name="无人能敌", description="在所有难度的“再战强敌”中击败所有敌人", english_name="Glutton for Punishment", hidden=true, english_description="Beat all Boss Rematch opponents on all difficulty levels.", group=4},
    {id="ACHIEVEMENT_028", name="剑路漫漫无止尽", description="完全习得并强化基本能力或特殊能力的其中一类", english_name="The Winding Way of the Sword", hidden=false, english_description="Learn and upgrade all basic or special skills.", group=2},
    {id="ACHIEVEMENT_029", name="武艺巅峰", description="强化所有基本能力与特殊能力", english_name="Well-Rounded", hidden=false, english_description="Learn and upgrade all basic and special skills.", group=2},
    {id="ACHIEVEMENT_030", name="保养不可少", description="初次强化装备", english_name="Looking Sharp", hidden=false, english_description="Enhance a piece of equipment for the first time.", group=2},
    {id="ACHIEVEMENT_031", name="完全武装", description="将所有装备强化至最高阶段", english_name="Dressed to Kill", hidden=false, english_description="Enhance all equipment to the maximum level.", group=2},
    {id="ACHIEVEMENT_032", name="鬼之武具收藏家", description="获得所有鬼之武具", english_name="Oni Armory", hidden=false, english_description="Acquire all Oni Armaments.", group=2},
    {id="ACHIEVEMENT_033", name="健康第一", description="将任意一种鬼灯袋强化至最高阶段", english_name="Health Is Wealth", hidden=false, english_description="Enhance a Hozuki Pouch to the maximum level.", group=2},
    {id="ACHIEVEMENT_034", name="滋补强身", description="将所有鬼灯袋强化至最高阶段", english_name="Medical Marvel", hidden=false, english_description="Enhance all Hozuki Pouches to the maximum level.", group=2},
    {id="ACHIEVEMENT_035", name="加护之力", description="将任意一种御守强化至最高阶段", english_name="A Real Charmer", hidden=false, english_description="Enhance a charm to the maximum level.", group=2},
    {id="ACHIEVEMENT_036", name="最强加护", description="将所有御守强化至最高阶段", english_name="Charmed Life", hidden=false, english_description="Enhance all charms to the maximum level.", group=2},
    {id="ACHIEVEMENT_037", name="燃烧的刀身", description="在气焰状态下击败50名敌人", english_name="Burning Blade", hidden=false, english_description="Defeat 50 foes while in the Blazing State.", group=3},
    {id="ACHIEVEMENT_038", name="视若停滞", description="施展50次看破连斩", english_name="Stop Motion", hidden=false, english_description="Perform 50 Reflex Combos.", group=3},
    {id="ACHIEVEMENT_039", name="掌控鬼之力", description="用鬼之武具击败100名敌人", english_name="Wielder of Oni Armaments", hidden=false, english_description="Defeat 100 enemies with Oni Armaments.", group=3},
    {id="ACHIEVEMENT_040", name="鬼族认可之人", description="在完全觉醒状态下击败50名敌人", english_name="Oni's Oni", hidden=false, english_description="Defeat 50 enemies in the Oni Awakened state.", group=3},
    {id="ACHIEVEMENT_041", name="干脆利落", description="成功施展50次一闪", english_name="Brutalist", hidden=false, english_description="Land 50 Issen attacks.", group=3},
    {id="ACHIEVEMENT_042", name="行云流水", description="用连锁一闪击败50名敌人", english_name="Flow State", hidden=false, english_description="Defeat 50 enemies with Chain Issen attacks.", group=3},
    {id="ACHIEVEMENT_043", name="偷感十足", description="用暗杀击败20名敌人", english_name="Silent Violence", hidden=false, english_description="Assassinate 20 enemies.", group=3},
    {id="ACHIEVEMENT_044", name="弹开高手", description="反弹远距离攻击50次", english_name="Pinch Hitter", hidden=false, english_description="Deflect 50 projectiles.", group=3},
    {id="ACHIEVEMENT_045", name="弓术高手", description="用弓攻击敌人的头部100次", english_name="Deadeye", hidden=false, english_description="Score 100 headshots with your bow.", group=3},
    {id="ACHIEVEMENT_046", name="能赢就行", description="利用场景物件攻击敌人50次", english_name="Winning Is What Matters", hidden=false, english_description="Carry out 50 attacks with environmental objects.", group=3},
    {id="ACHIEVEMENT_047", name="摧枯拉朽", description="成功反抓50次", english_name="Untouchable", hidden=false, english_description="Perform 50 Grab Reversals.", group=3},
    {id="ACHIEVEMENT_048", name="强行突破", description="击溃敌人的防御50次", english_name="Coming Through!", hidden=false, english_description="Break an enemy's guard 50 times.", group=3},
    {id="ACHIEVEMENT_049", name="破坏的化身", description="破坏敌人的盔甲或盾牌100次", english_name="Helm Splitter", hidden=false, english_description="Break 100 shields or pieces of enemy armor.", group=3},
    {id="ACHIEVEMENT_050", name="只为摘下笼手", description="一次性吸收不少于30个灵魂", english_name="Get This Thing Off Me", hidden=false, english_description="Absorb 30 or more souls at once.", group=3},
    {id="ACHIEVEMENT_051", name="兵败如山倒", description="用连续崩之一闪击败3名敌人", english_name="Berserker", hidden=false, english_description="Defeat 3 enemies with continuous Break Issen attacks.", group=3},
    {id="ACHIEVEMENT_052", name="幻魔弱火", description="一次性让3名敌人陷入剧烈燃烧状态", english_name="Genma Griller", hidden=false, english_description="Set three enemies ablaze at once.", group=3},
}
